## test
##' Run the Python Preprocessing Pipeline
##'
##' This function runs the three Python preprocessing steps:
##' 1. Generate the single-cell barcode file.
##' 2. Run the fragment overlap counter.
##' 3. Process the overlap counter output.
##'
##' @param filtered_h5 Path to the filtered_feature_bc_matrix.h5 file.
##' @param raw_h5 Path to the raw_feature_bc_matrix.h5 file.
##' @param atac_fragments Path to the atac_fragments.tsv.gz file.
##' @param human_autosomes Path to the human_autosomes.txt file.
##' @param output_directory Directory where all outputs will be saved.
##' @param py_dir Directory where the Python scripts are located.
##' @param rfilter_file Optional path to a repetitive regions filter file.
##'
##' @return The path to the final output file ("colsum.csv") generated by the Python pipeline.
##'
##' @export
run_preprocessing_pipeline <- function(filtered_h5, raw_h5, atac_fragments, human_autosomes,
                                       output_directory, py_dir, rfilter_file = "") {
  # Ensure output directory exists
  if (!dir.exists(output_directory)) {
    dir.create(output_directory, recursive = TRUE)
  }
  
  # Step 1: Generate singlecell.csv
  singlecell_cmd <- sprintf(
    "python %s/generate_singlecell.py --filtered-h5 %s --raw-h5 %s --output %s",
    py_dir, filtered_h5, raw_h5, output_directory
  )
  message("Running generate_singlecell.py...")
  system(singlecell_cmd)
  
  singlecell_csv <- file.path(output_directory, "singlecell.csv")
  
  # Step 2: Run FragmentFileOverlapCounter.py
  frag_cmd <- sprintf(
    "python3 %s/FragmentFileOverlapCounter.py %s %s %s %s",
    py_dir, atac_fragments, singlecell_csv, human_autosomes, output_directory
  )
  message("Running FragmentFileOverlapCounter.py...")
  system(frag_cmd)
  
  # Step 3: Run process_overlap_counter.py
  overlaps_file <- file.path(output_directory, "Overlaps.txt")
  overlap_summary_file <- file.path(output_directory, "OverlapSummary.txt")
  
  process_cmd <- sprintf(
    "python3 %s/process_overlap_counter.py --overlaps %s --overlap-summary %s --output-dir %s",
    py_dir, overlaps_file, overlap_summary_file, output_directory
  )
  
  if (nzchar(rfilter_file)) {
    process_cmd <- sprintf("%s --rfilter %s", process_cmd, rfilter_file)
  }
  
  message("Running process_overlap_counter.py...")
  system(process_cmd)
  
  colsum_csv <- file.path(output_directory, "colsum.csv")
  if (!file.exists(colsum_csv)) {
    stop("Preprocessing failed: colsum.csv not found.")
  }
  
  message("Preprocessing pipeline completed successfully.")
  return(colsum_csv)
}




##' Run the Detection Step on Preprocessed Data
##'
##' This function runs the R-based doublet detection on the preprocessed data.
##'
##' @param input Either a file path to the preprocessed CSV (e.g., colsum.csv) or a data frame.
##' @param ... Additional parameters to pass to \code{doublet_cm()}.
##'
##' @return A list with doublet detection results.
##'
##' @export
run_detection <- function(input, ...) {
  if (is.character(input) && file.exists(input)) {
    data <- readr::read_csv(input)
  } else if (is.data.frame(input)) {
    data <- input
  } else {
    stop("Input must be a file path or a data frame containing the preprocessed data.")
  }
  
  colnames(data) <- c("barcode", "obs")
  message("Running doublet detection in R...")
  # For demonstration, using nulltype = 2 and default parameters.
  result <- doublet_cm(data, truncation_point = 0, pct0 = c(0.2, 0.6), nulltype = 2, thres = 0.2, ...)
  return(result)
}
